In [1]:
import numpy as np

In [2]:
a = np.random.randn(2, 3) # a.shape = (2, 3)
b = np.random.randn(2, 1) # b.shape = (2, 1)
c = a + b

In [3]:
c.shape

(2, 3)

In [4]:
a = np.random.randn(4, 3) # a.shape = (4, 3)
b = np.random.randn(3, 2) # b.shape = (3, 2)
c = a*b

ValueError: operands could not be broadcast together with shapes (4,3) (3,2) 

In [5]:
a = np.random.randn(12288, 150) # a.shape = (12288, 150)
b = np.random.randn(150, 45) # b.shape = (150, 45)
c = np.dot(a,b)

In [6]:
c.shape

(12288, 45)

In [16]:
a = np.random.randn(3, 4) # a.shape = (4, 3)
b = np.random.randn(4, 1) # b.shape = (3, 2)
for i in range(3):
  for j in range(4):
    c[i][j] = a[i][j] + b[j]

In [13]:
print(c)

[[ 0.95946523  0.14933948 -0.89544865  0.80465776]
 [ 0.2494746  -0.42898785  0.56034111 -0.26094218]
 [ 0.22175645  1.51625785 -0.20514787 -0.25813746]]


In [14]:
c = a + b.T

In [15]:
print(c)

[[ 0.95946523  0.14933948 -0.89544865  0.80465776]
 [ 0.2494746  -0.42898785  0.56034111 -0.26094218]
 [ 0.22175645  1.51625785 -0.20514787 -0.25813746]]


In [17]:
a = np.random.randn(3, 4) # a.shape = (4, 3)
b = np.random.randn(4, 1) # b.shape = (3, 2)
for i in range(3):
  for j in range(4):
    c[i][j] = a[i][j] + b[j]

In [18]:
print(c)

[[-0.6629337  -0.12182372 -1.4734033  -3.02842107]
 [-1.26000055  0.36485215 -2.11110729  0.85624856]
 [-2.84247311  0.85667454 -0.83323188 -0.45948052]]


In [21]:
c = a.T + b

In [22]:
print(c)

[[-0.6629337  -1.26000055 -2.84247311]
 [-0.12182372  0.36485215  0.85667454]
 [-1.4734033  -2.11110729 -0.83323188]
 [-3.02842107  0.85624856 -0.45948052]]


In [23]:
a = np.random.randn(3, 3)
b = np.random.randn(3, 1)
c = a*b

In [24]:
print(c)

[[ 2.07671231e-03 -8.24374975e-05 -7.48385249e-03]
 [-1.19069272e+00 -9.32888687e-01 -1.11236272e+00]
 [-8.16662646e-01  8.95255012e-01  1.74197912e-03]]


In [25]:
print(a)

[[-0.24765764  0.00983106  0.89248435]
 [-1.36506394 -1.06950575 -1.27526288]
 [ 1.12192372 -1.2298932  -0.00239312]]


In [26]:
print(b)

[[-0.00838542]
 [ 0.8722615 ]
 [-0.72791281]]
