In [1]:
import numpy as np

a = np.array([1,2,3,4,5])  # Creating a numpy python vector

In [2]:
print(a)

[1 2 3 4 5]


In [3]:
import time    # To calculate time of execution

a = np.random.rand(1000000)  # Creating a million dimensional array
b = np.random.rand(1000000)  # Creating a million dimensional array

In [4]:
start = time.time()
c = np.dot(a,b) # Dot product of a and b
end = time.time()

print(c)

250356.50918136144


In [5]:
print("Vectorized Version : "+str((end-start)*1000)+" ms")

Vectorized Version : 1350.252389907837 ms


In [6]:
c = 0

start = time.time()
for i in range(1000000):
    c += a[i]*b[i]
end = time.time()

print("Normal Version : "+str(1000*(end-start))+" ms")

Normal Version : 734.4164848327637 ms


In [7]:
print(c)

250356.50918135888


### Here vectorized version has executed in time nearly 300 times faster than normal multiplication done by using for loop

In [8]:
u = np.zeros((10,1))

In [9]:
print(u)

[[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]]


In [10]:
import math
x = math.exp(1)

In [11]:
print(x)

2.718281828459045


In [12]:
a = np.random.rand(1000000)

In [13]:
print(a)

[0.2256235  0.94006489 0.73578453 ... 0.23843476 0.01663477 0.19772755]


In [14]:
a.shape

(1000000,)